[package]
name = "rustBCA"
version = "0.1.0"
authors = ["Jon Drobny <drobny2@illinois.edu>"]
edition = "2018"

[[bin]]
name="rustBCA"

[dependencies]
rand = "0.7.3"
geo = "0.14.2"
serde = { version = "1.0.116", features = ["derive"] }
toml = "0.5.6"
float-cmp = "0.8.0"
anyhow = "1.0.32"
hdf5 = {version = "0.7.0", optional = true}
rayon = "1.4.0"
openblas-src = {version  = "0.9", optional = true}
rcpr = { path = "../rcpr", optional = true}
indicatif = {version="*", features=["rayon"]}
itertools = ""

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true

[features]
hdf5_input = ["hdf5"]
cpr_rootfinder = ["rcpr", "openblas-src"]
