[package]
name = "rustBCA"
version = "0.1.0"
authors = ["Jon Drobny <drobny2@illinois.edu>"]
edition = "2018"

[[bin]]
name="rustBCA"

[dependencies]
rand = "0.7.3"
geo = "0.14.2"
serde = { version = "1.0.116", features = ["derive"] }
toml = "0.5.6"
float-cmp = "0.8.0"
anyhow = "1.0.32"
hdf5 = {version = "0.7.0", optional = true}
rayon = "1.4.0"
openblas-src = {version  = "0.9", optional = true}
netlib-src = {version  = "0.8", optional = true}
intel-mkl-src = {version = "0.6.0", optional = true}
rcpr = { git = "https://github.com/drobnyjt/rcpr", optional = true}
indicatif = {version="*", features=["rayon"]}
itertools = "0.9.0"
ndarray = {version = "0.14.0", optional = true, features = ["serde"]}

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true

[features]
hdf5_input = ["hdf5"]
cpr_rootfinder_openblas = ["rcpr", "openblas-src"]
cpr_rootfinder_netlib = ["rcpr", "netlib-src"]
cpr_rootfinder_intel_mkl = ["rcpr", "intel-mkl-src"]
distributions = ["ndarray"]
no_list_output = []
