[package]
name = "rustBCA"
version = "0.1.0"
authors = ["Jon Drobny <drobny2@illinois.edu>"]
edition = "2018"

[dependencies]
rand = "0.7"
geo = "0.12.2"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
float-cmp = "0.5.2"

[profile.release]
lto = "fat"
codegen-units = 1
target-cpu = "native"
