name: rustBCA Compile check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install curl
      run: |
        sudo apt-get install curl
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
    - name: Install pip for Python-3
      run: |
        sudo apt-get install python3-pip
    - name: Install Python libraries
      run: |
        python3 -m pip install numpy shapely scipy
    - name: Install python TOML library from source
      run: |
        git clone https://github.com/uiri/toml.git
        cd toml
        sudo python3 setup.py install
    - name: Install HDF5 Libraries
      run: |
        sudo apt install libhdf5-dev
    - name: Test RustBCA
      run: |
        cargo test --features cpr_rootfinder_netlib,hdf5_input,distributions,parry3d
    - name: Run Examples
      run: |
        cargo run --release 0D examples/boron_nitride_0D.toml
        ./target/release/rustBCA 0D examples/titanium_dioxide_0D.toml
        ./target/release/rustBCA 1D examples/layered_geometry_1D.toml
        cat 2000.0eV_0.0001deg_He_TiO2_Al_Sisummary.output
        ./target/release/rustBCA examples/boron_nitride.toml
        ./target/release/rustBCA examples/layered_geometry.toml
        cat 2000.0eV_0.0001deg_He_TiO2_Al_Sisummary.output
        ./target/release/rustBCA SPHERE examples/boron_nitride_sphere.toml
        cargo run --release --features parry3d TRIMESH examples/tungsten_twist_trimesh.toml
