name: rustBCA Compile check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install curl
      run: |
        sudo apt-get install curl
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
    - name: Install pip for Python-3
      run: |
        sudo apt-get install python3-pip
    - name: Install Python libraries
      run: |
        pip3 
        python3 -m pip install numpy shapely scipy
    - name: Install python TOML library from source
      run: |
        git clone https://github.com/uiri/toml.git
        cd toml
        sudo python3 setup.py install
    - name: Install HDF5 Libraries
      run: |
        sudo apt install libhdf5-dev
    - name: Test RustBCA
      run: |
        cargo test --features cpr_rootfinder_netlib,hdf5_input
    - name: Run Examples
      run: |
        cargo run --release examples/boron_nitride.toml
        cargo run --release examples/layered_geometry.toml
